# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71ef8de7df3ff0dd60def3ac3cc715f4a18aacc50e4705a03e161d8a5d17a1c6dc2b1480229cf4cb6766932117bd0a042bc5434b8af96340394f05aa237f89da

test:
  secret_key_base: 217d37209d989a8b4676039e177bf81e3f4afdb3ee9922c9b5407f8fa733449cdd03c71dc6db0a675cfb3e271865de616db532ddd623790bf62ea2ed4933e0d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
